/**
 * Nord theme example
 *
 * Run: npx ts-node examples/themes/nord.ts
 */

import shellfie, { nord } from '../../src';
import { writeFileSync } from 'node:fs';

const terminalOutput = `\x1b[1;32m❯\x1b[0m git log --oneline --graph
\x1b[1;31m*\x1b[0m   \x1b[1;33me4f5a6b\x1b[0m \x1b[1;36m(HEAD -> main)\x1b[0m Merge pull request #42
\x1b[1;31m|\\
\x1b[0m\x1b[1;31m| *\x1b[0m \x1b[1;33m9c8d7e6\x1b[0m \x1b[32mfeat: add dark mode support\x1b[0m
\x1b[1;31m| *\x1b[0m \x1b[1;33m5b4a3c2\x1b[0m \x1b[32mstyle: update color palette\x1b[0m
\x1b[1;31m|/
\x1b[0m\x1b[1;31m*\x1b[0m   \x1b[1;33m1a2b3c4\x1b[0m \x1b[1;36m(origin/main)\x1b[0m Merge branch 'feature/auth'
\x1b[1;31m|\\
\x1b[0m\x1b[1;31m| *\x1b[0m \x1b[1;33mf7e6d5c\x1b[0m \x1b[32mfeat: implement OAuth2 flow\x1b[0m
\x1b[1;31m| *\x1b[0m \x1b[1;33mb8a9c0d\x1b[0m \x1b[32mchore: add auth dependencies\x1b[0m
\x1b[1;31m|/
\x1b[0m\x1b[1;31m*\x1b[0m   \x1b[1;33m2d3e4f5\x1b[0m \x1b[32mfix: resolve memory leak in worker\x1b[0m
\x1b[1;31m*\x1b[0m   \x1b[1;33m6g7h8i9\x1b[0m \x1b[32mdocs: update API reference\x1b[0m`;

const svg = shellfie(terminalOutput, {
  template: 'macos',
  theme: nord,
  title: 'Nord',
  watermarkPadding: 20,
  watermark: '\x1b[38;5;242mGenerated by shellfie\x1b[0m'
});

writeFileSync('examples/svgs/themes/nord.svg', svg);
console.log('✓ Created examples/svgs/themes/nord.svg');
