import Chartscii from 'chartscii';
import { snaptty } from '../src';
import { writeFileSync } from 'fs';

const colors = [
    'red',
    'green',
    'yellow',
    'blue',
    'purple',
    'pink',
    'cyan',
    'orange',
    'purple',
    'marine',
];

const data = []

for (let i = 0; i < colors.length; i++) {
    const color = colors[i];
    data.push({ value: i + 1, color, label: `@invert ${i}@` });
}

const chart = new Chartscii(data, {
    barSize: 2,
    fill: '▒',
    colorLabels: true,
    orientation: 'vertical',
    valueLabels: true
});

const svg = snaptty(chart.create(), {
    template: 'macos',
    title: 'Chartscii',
    padding: 50,
    watermark: 'Generated by snaptty',
});

writeFileSync('examples/svgs/chartscii.svg', svg);
