/**
 * highlight example
 *
 * Run: npx ts-node examples/highlight.ts
 */

import shellfie, { themes } from '../src';
import { writeFileSync } from 'node:fs';

const terminalOutput = `
#!/bin/bash

echo "Hello World!"
`
const svg = shellfie(terminalOutput, {
  template: 'macos',
  width: 300,
  theme: themes.draculaPro,
  title: 'Syntax highlighting',
  watermark: '\x1b[38;5;242mGenerated by shellfie\x1b[0m'
});

writeFileSync('examples/svgs/highlight.svg', svg);
console.log('✓ Created examples/svgs/higlight.svg');