import { describe, it, expect } from 'vitest';
import {
  shellfie,
  parse,
  render,
  templates,
  darkTheme,
} from '.';

describe('shellfie', () => {
  it('renders plain text to SVG', () => {
    const svg = shellfie('Hello World');
    expect(svg).toContain('<svg');
    expect(svg).toContain('</svg>');
    expect(svg).toContain('Hello World');
  });

  it('renders colored text', () => {
    const svg = shellfie('\x1b[31mRed\x1b[0m');
    expect(svg).toContain('Red');
    expect(svg).toContain('#cd3131'); // dark theme red
  });

  it('renders with macOS template by default', () => {
    const svg = shellfie('Test', { controls: true });
    // macOS has traffic light buttons
    expect(svg).toContain('#ff5f56'); // close button color
    expect(svg).toContain('#ffbd2e'); // minimize button color
    expect(svg).toContain('#27c93f'); // maximize button color
  });

  it('renders with windows template', () => {
    const svg = shellfie('Test', { template: 'windows', controls: true });
    expect(svg).toContain('#e81123'); // windows close button color
  });

  it('renders with minimal template', () => {
    const svg = shellfie('Test', { template: 'minimal' });
    // Should not have window controls
    expect(svg).not.toContain('#ff5f56');
    expect(svg).not.toContain('#e81123');
  });

  it('renders with custom title', () => {
    const svg = shellfie('Test', { title: 'My Terminal' });
    expect(svg).toContain('My Terminal');
  });

  it('renders with watermark', () => {
    const svg = shellfie('Test', { watermark: 'Generated by shellfie' });
    expect(svg).toContain('Generated by shellfie');
  });

  it('handles multiline input', () => {
    const svg = shellfie('Line 1\nLine 2\nLine 3');
    expect(svg).toContain('Line 1');
    expect(svg).toContain('Line 2');
    expect(svg).toContain('Line 3');
  });

  it('escapes XML special characters', () => {
    const svg = shellfie('<script>alert("XSS")</script>');
    expect(svg).not.toContain('<script>');
    expect(svg).toContain('&lt;script&gt;');
  });

  it('handles empty input', () => {
    const svg = shellfie('');
    expect(svg).toContain('<svg');
    expect(svg).toContain('</svg>');
  });

  it('renders bold text', () => {
    const svg = shellfie('\x1b[1mBold\x1b[0m');
    expect(svg).toContain('font-weight="bold"');
  });

  it('renders italic text', () => {
    const svg = shellfie('\x1b[3mItalic\x1b[0m');
    expect(svg).toContain('font-style="italic"');
  });

  it('renders underlined text', () => {
    const svg = shellfie('\x1b[4mUnderlined\x1b[0m');
    expect(svg).toContain('text-decoration="underline"');
  });

  it('renders 256-color', () => {
    const svg = shellfie('\x1b[38;5;196mColor 196\x1b[0m');
    expect(svg).toContain('#ff0000'); // 256-color 196 is red
  });

  it('renders 24-bit RGB color', () => {
    const svg = shellfie('\x1b[38;2;100;150;200mRGB\x1b[0m');
    expect(svg).toContain('#6496c8');
  });

  it('applies custom font size', () => {
    const svg = shellfie('Test', { fontSize: 20 });
    expect(svg).toContain('font-size="20"');
  });

  it('applies custom padding', () => {
    const svg = shellfie('Test', { padding: 32 });
    // SVG should be wider due to more padding
    const defaultSvg = shellfie('Test', { padding: 16 });
    const widthMatch = svg.match(/width="(\d+)"/);
    const defaultWidthMatch = defaultSvg.match(/width="(\d+)"/);
    expect(Number(widthMatch?.[1])).toBeGreaterThan(Number(defaultWidthMatch?.[1]));
  });
});

describe('parse', () => {
  it('returns parsed lines', () => {
    const lines = parse('\x1b[31mRed\x1b[0m Normal');
    expect(lines).toHaveLength(1);
    expect(lines[0].spans).toHaveLength(2);
  });
});

describe('render', () => {
  it('renders parsed lines to SVG', () => {
    const lines = parse('Hello World');
    const svg = render(lines);
    expect(svg).toContain('<svg');
    expect(svg).toContain('Hello World');
  });
});

describe('templates', () => {
  it('exports all templates', () => {
    expect(templates.macos).toBeDefined();
    expect(templates.windows).toBeDefined();
    expect(templates.minimal).toBeDefined();
  });

  it('macos template has correct configuration', () => {
    expect(templates.macos.name).toBe('macos');
    expect(templates.macos.shell.controlsPosition).toBe('left');
    expect(templates.macos.shell.borderRadius).toBe(10);
  });

  it('windows template has correct configuration', () => {
    expect(templates.windows.name).toBe('windows');
    expect(templates.windows.shell.controlsPosition).toBe('right');
    expect(templates.windows.shell.borderRadius).toBe(0);
  });

  it('minimal template has no shell decorations', () => {
    expect(templates.minimal.name).toBe('minimal');
    expect(templates.minimal.shell.titleBar).toBe(false);
    expect(templates.minimal.shell.controls).toBe(false);
  });
});

describe('darkTheme', () => {
  it('has all required colors', () => {
    expect(darkTheme.background).toBeDefined();
    expect(darkTheme.foreground).toBeDefined();
    expect(darkTheme.black).toBeDefined();
    expect(darkTheme.red).toBeDefined();
    expect(darkTheme.green).toBeDefined();
    expect(darkTheme.yellow).toBeDefined();
    expect(darkTheme.blue).toBeDefined();
    expect(darkTheme.magenta).toBeDefined();
    expect(darkTheme.cyan).toBeDefined();
    expect(darkTheme.white).toBeDefined();
    expect(darkTheme.brightBlack).toBeDefined();
    expect(darkTheme.brightRed).toBeDefined();
    expect(darkTheme.brightGreen).toBeDefined();
    expect(darkTheme.brightYellow).toBeDefined();
    expect(darkTheme.brightBlue).toBeDefined();
    expect(darkTheme.brightMagenta).toBeDefined();
    expect(darkTheme.brightCyan).toBeDefined();
    expect(darkTheme.brightWhite).toBeDefined();
  });
});

describe('integration', () => {
  it('handles complex ANSI output (simulated ls --color)', () => {
    const input = [
      '\x1b[1;34mdir1\x1b[0m  \x1b[1;34mdir2\x1b[0m  \x1b[32mfile.txt\x1b[0m',
      '\x1b[1;36mlink\x1b[0m  \x1b[33mwarning.log\x1b[0m',
    ].join('\n');

    const svg = shellfie(input);
    expect(svg).toContain('dir1');
    expect(svg).toContain('dir2');
    expect(svg).toContain('file.txt');
    expect(svg).toContain('link');
    expect(svg).toContain('warning.log');
  });

  it('handles git diff-like output', () => {
    const input = [
      '\x1b[1mdiff --git a/file.ts b/file.ts\x1b[0m',
      '\x1b[36m@@ -1,3 +1,4 @@\x1b[0m',
      ' const a = 1;',
      '\x1b[31m-const b = 2;\x1b[0m',
      '\x1b[32m+const b = 3;\x1b[0m',
      '\x1b[32m+const c = 4;\x1b[0m',
    ].join('\n');

    const svg = shellfie(input, { title: 'git diff' });
    expect(svg).toContain('diff --git');
    expect(svg).toContain('const b = 2');
    expect(svg).toContain('const b = 3');
    expect(svg).toContain('git diff');
  });

  it('handles npm output with colors', () => {
    const input = [
      '\x1b[32mnpm\x1b[0m \x1b[36mWARN\x1b[0m deprecated package@1.0.0',
      '\x1b[32mnpm\x1b[0m \x1b[31mERR!\x1b[0m code ERESOLVE',
    ].join('\n');

    const svg = shellfie(input);
    expect(svg).toContain('npm');
    expect(svg).toContain('WARN');
    expect(svg).toContain('ERR!');
  });
});
