import type { AnimationType } from './animations';

export interface RGB {
  r: number;
  g: number;
  b: number;
}

export interface Gradient {
  type: 'gradient';
  colors: string[];
  direction?: 'horizontal' | 'vertical' | 'diagonal';
  reverse?: boolean;
}

export type PatternType = 'grid' | 'dots' | 'stripes' | 'crosshatch' | 'diagonal-stripes';

export interface PatternConfig {
  type: PatternType;
  color?: string;
  size?: number;
  strokeWidth?: number;
}

export interface BackgroundConfig {
  color: string | Gradient;
  padding?: number;
  borderRadius?: number;
  pattern?: PatternType | PatternConfig;
}

export interface TextStyle {
  foreground?: string | RGB;
  background?: string | RGB;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  strikethrough?: boolean;
  dim?: boolean;
  inverse?: boolean;
}

export interface TextSpan {
  text: string;
  style: TextStyle;
}

export interface ParsedLine {
  spans: TextSpan[];
}

export interface Theme {
  name: string;
  background: string;
  foreground: string;
  cursor: string;
  selection: string;
  headerBackground?: string;
  footerBackground?: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}

export interface ControlStyle {
  close: string;
  minimize: string;
  maximize: string;
  radius: number;
  spacing: number;
  size: number;
}

export interface HeaderConfig {
  backgroundColor?: string;
  height?: number;
  border?: boolean | string;
  borderColor?: string;
  borderWidth?: number;
}

export interface FooterConfig {
  backgroundColor?: string;
  height?: number;
  border?: boolean | string;
  borderColor?: string;
  borderWidth?: number;
}

export interface ShellConfig {
  titleBar: boolean;
  titleBarHeight: number;
  borderRadius: number;
  controls: boolean;
  controlsPosition: 'left' | 'right';
  controlStyle: ControlStyle;
  padding: number;
  shadow: boolean;
  border: boolean | string;
  borderColor: string | Gradient;
  borderWidth: number;
  header?: HeaderConfig;
  footer?: FooterConfig;
}

export interface Template {
  name: string;
  shell: ShellConfig;
}

export type PaddingInput = number | [number, number] | [number, number, number, number];

export interface ResolvedPadding {
  top: number;
  right: number;
  bottom: number;
  left: number;
}

export interface FontConfig {
  family: string;
  size: number;
  lineHeight: number;
  charWidth: number;
  embedData?: string;
  embedFormat?: 'woff2' | 'woff' | 'ttf';
}

/**
 * CSS shorthand notation for padding/margin.
 * - number: Same value on all sides
 * - [vertical, horizontal]: Top/bottom and left/right
 * - [top, right, bottom, left]: Individual sides
 */
export type CSSShorthand = number | [number, number] | [number, number, number, number];

/**
 * CSS-like style properties for watermark positioning and appearance.
 * Supports standard CSS properties that are applicable to SVG elements.
 */
export interface WatermarkStyle {
  /**
   * Padding around the watermark. Supports CSS shorthand notation.
   * - number: Same padding on all sides
   * - [vertical, horizontal]: Top/bottom and left/right
   * - [top, right, bottom, left]: Individual sides
   */
  padding?: CSSShorthand;
  paddingTop?: number;
  paddingRight?: number;
  paddingBottom?: number;
  paddingLeft?: number;

  /**
   * Margin around the watermark. Supports CSS shorthand notation.
   * - number: Same margin on all sides
   * - [vertical, horizontal]: Top/bottom and left/right
   * - [top, right, bottom, left]: Individual sides
   */
  margin?: CSSShorthand;
  marginTop?: number;
  marginRight?: number;
  marginBottom?: number;
  marginLeft?: number;

  // Visual properties
  opacity?: number;
  filter?: string;
  transform?: string;

  // Allow any additional CSS properties
  [key: string]: CSSShorthand | string | number | undefined;
}

/**
 * Resolved style with all values explicitly set for rendering.
 */
export interface ResolvedWatermarkStyle {
  paddingTop: number;
  paddingRight: number;
  paddingBottom: number;
  paddingLeft: number;
  marginTop: number;
  marginRight: number;
  marginBottom: number;
  marginLeft: number;
  // Additional CSS properties as a style string for the SVG element
  cssString: string;
}

export interface WatermarkConfig {
  /**
   * Watermark content - either plain text (with optional ANSI codes) or raw SVG markup.
   *
   * Text content:
   * @example 'Generated by shellfie'
   * @example '\x1b[90mGenerated by shellfie\x1b[0m'
   *
   * SVG markup - must be valid SVG elements (not HTML). Wrapped in a <g> element
   * positioned at the bottom-right corner with font-family, font-size, and fill inherited from theme.
   * @example '<text text-anchor="end">Powered by shellfie</text>'
   * @example '<a href="https://example.com"><text text-anchor="end">Click here</text></a>'
   */
  content: string;

  /**
   * Content type: 'text' for plain text (supports ANSI), 'markup' for raw SVG.
   * Auto-detected based on content: if content starts with '<', it's treated as markup.
   * Only specify explicitly if auto-detection doesn't work for your use case.
   */
  type?: 'text' | 'markup';

  /**
   * CSS-like style properties for positioning and appearance.
   */
  style?: WatermarkStyle;
}

export type Preset = Omit<shellfieOptions, 'preset'>;

export interface shellfieOptions {
  preset?: 'browserbase' | 'clerk' | 'cloudflare' | 'elevenlabs' | 'firecrawl' | 'gemini' | 'mintlify' | 'nuxt' | 'openai' | 'prisma' | 'resend' | 'supabase' | 'tailwind' | 'triggerdev' | 'vercel' | (string & {}) | Preset;
  template?: 'macos' | 'windows' | 'minimal' | Template;
  title?: string;
  titleAlignment?: 'left' | 'center' | 'right';
  titleStyle?: 'text' | 'tab-underline' | 'tab-box';
  theme?: Theme;
  fontSize?: number;
  lineHeight?: number;
  padding?: PaddingInput;
  width?: number; // If provided, sets exact SVG width (auto-size if omitted)
  height?: number; // If provided, sets exact SVG height (auto-size if omitted)
  /**
   * Watermark displayed at the bottom-right of the SVG.
   * - String: Text with optional ANSI codes (e.g., "\x1b[90mGenerated by shellfie\x1b[0m")
   * - WatermarkConfig: Object with content, type, and style
   */
  watermark?: string | WatermarkConfig;
  controls?: boolean;
  controlsPosition?: 'left' | 'right';
  fontFamily?: string;
  embedFont?: boolean;
  customFont?: {
    data: string;
    format: 'woff2' | 'woff' | 'ttf';
  };
  customGlyphs?: boolean;
  header?: HeaderConfig;
  footer?: FooterConfig;
  /**
   * Syntax highlighting language.
   * - 'auto': Auto-detect language from code content (default)
   * - Language name: Use specific language (e.g., 'typescript', 'python', 'bash')
   * - false: Disable highlighting (preserves existing ANSI codes in input)
   */
  language?: 'auto' | 'bash' | 'javascript' | 'typescript' | 'python' | 'json' | 'go' | 'rust' | 'java' | 'c' | 'cpp' | 'csharp' | 'html' | (string & {}) | false;
  /**
   * Background color or gradient for the outer container surrounding the terminal.
   *
   * Can be specified as:
   * - String: Hex color or gradient string
   *   @example '#1a1a2e'
   *   @example 'gradient(#ff0000, #0000ff)'
   *   @example 'gradient(#ff0000, #0000ff:diagonal:reverse)'
   *
   * - Object: { color, padding? } for explicit padding control
   *   @example { color: '#1a1a2e', padding: 30 }
   *   @example { color: 'gradient(#ff0000, #0000ff:vertical)', padding: 40 }
   *
   * Gradient directions: 'horizontal' (default), 'vertical', 'diagonal'
   * Use :reverse to reverse color order
   *
   * @default padding is 20 when background is set
   */
  background?: string | BackgroundConfig;
  lineNumbers?: boolean | {
    color?: string;
    startFrom?: number;
  };
  badge?: boolean | {
    label?: string;
    color?: string;
    backgroundColor?: string;
    borderRadius?: number;
    borderColor?: string;
    borderWidth?: number;
    opacity?: number;
  };
  backgroundOpacity?: number;
  borderColor?: string;
  glow?: boolean | {
    color?: string;
    strength?: number;
    opacity?: number;
  };
  overlays?: string | string[] | ((width: number, height: number) => string | string[]);
  animation?: AnimationType;
  animationColor?: string;
}

export interface ResolvedHeaderConfig {
  backgroundColor: string;
  height: number;
  border: boolean;
  borderColor: string;
  borderWidth: number;
}

export interface ResolvedFooterConfig {
  backgroundColor: string;
  height: number;
  border: boolean;
  borderColor: string;
  borderWidth: number;
}

export interface ResolvedWatermark {
  type: 'text' | 'markup';
  content: string;
  style: ResolvedWatermarkStyle;
}

export interface ResolvedBackground {
  value: string | Gradient;
  padding: number;
  borderRadius: number;
  pattern: ResolvedPattern | null;
}

export interface ResolvedPattern {
  type: PatternType;
  color: string;
  size: number;
  strokeWidth: number;
}

export interface ResolvedLineNumbers {
  color: string;
  startFrom: number;
}

export interface ResolvedBadge {
  label: string;
  color: string;
  backgroundColor: string | null;
  borderRadius: number | null;
  borderColor: string | null;
  borderWidth: number;
  opacity: number;
}

export interface ResolvedGlow {
  color: string;
  strength: number;
  opacity: number;
}

export interface RenderOptions {
  template: Template;
  title: string;
  titleAlignment: 'left' | 'center' | 'right';
  titleStyle: 'text' | 'tab-underline' | 'tab-box';
  theme: Theme;
  font: FontConfig;
  padding: ResolvedPadding;
  width: number | null;
  height: number | null;
  watermark: ResolvedWatermark | null;
  header: ResolvedHeaderConfig | null;
  footer: ResolvedFooterConfig | null;
  controls: boolean;
  customGlyphs: boolean;
  background: ResolvedBackground | null;
  lineNumbers: ResolvedLineNumbers | null;
  badge: ResolvedBadge | null;
  backgroundOpacity: number;
  glow: ResolvedGlow | null;
  overlays: shellfieOptions['overlays'];
  animation: AnimationType | null;
  animationColor: string | null;
}
